src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BienRepository::class)]
class Bien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $is_locatif = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 100)]
    private ?string $ville = null;

    #[ORM\Column(length: 5)]
    private ?string $cp = null;

    #[ORM\Column]
    private ?int $surface = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $id_categorie = null;

    #[ORM\ManyToMany(targetEntity: UserFav::class, mappedBy: 'id_bien')]
    private ?Collection $userFavs = null;

    #[ORM\Column(length: 255)]
    private ?string $ref = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isIsLocatif(): ?bool
    {
        return $this->is_locatif;
    }

    public function setIsLocatif(bool $is_locatif): self
    {
        $this->is_locatif = $is_locatif;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getIdCategorie(): ?categorie
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(?categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getUserFavs()
    {
        return $this->userFavs;
    }

    public function addUserFav(UserFav $userFav): self
    {
        if (!$this != null && !$this->userFavs->contains($userFav)) {
            $this->userFavs->add($userFav);
            $userFav->addIdBien($this);
        }

        return $this;
    }

    public function removeUserFav(UserFav $userFav): self
    {
        if ($this->userFavs->removeElement($userFav)) {
            $userFav->removeIdBien($this);
        }

        return $this;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function __toString()
    {
        return strval($this->getId());
    }
}

src/Form/BienType.php
<?php

namespace App\Form;

use App\Entity\Bien;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BienType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('is_locatif')
            ->add('prix')
            ->add('ville')
            ->add('cp')
            ->add('surface')
            ->add('ref')
            ->add('image')
            ->add('id_categorie')
            ->add('userFavs')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Bien::class,
        ]);
    }
}

src/Controller/BienController.php
<?php

namespace App\Controller;

use App\Repository\BienRepository;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BienController extends AbstractController
{
    #[Route('/bien', name: 'app_bien')]
    /**
     * Si l'utilisateur a sélectionné une catégorie, un type et un emplacement, alors nous affichons les propriétés
     * correspondantes. Sinon, nous affichons toutes les propriétés
     *
     * @param BienRepository bienRepository Le référentiel de l'entité Bien.
     * @param CategorieRepository categorieRepository Le référentiel de l'entité Catégorie.
     *
     * @return Response La fonction index renvoie le rendu du fichier index.html.twig.
     */
    public function index(BienRepository $bienRepository, CategorieRepository $categorieRepository): Response
    {

        if (!empty($_POST['Price'])) {
            $price = $_POST['Price'];
        } else {
            $price = 999999;
        }


        if (isset($_POST["Categ"]) && isset($_POST["Type"]) && isset($_POST["local"])) {

            $id = ($_POST["Categ"]);
            $type = $_POST["Type"];
            $local = $_POST["local"];


            $intitCateg = $categorieRepository->affichageIntit($id);
            $intitType = ($type == 0) ? 'Achat' : 'Location';


            if ($id == "") {
                if ($type == "") {
                    if ($local == "") {
                        $lesBiens = $bienRepository->findAll();
                        $titre = 'Affichage des biens';
                    } else {
                        $lesBiens = $bienRepository->findBy(['cp' => $local]);
                        $titre = "Affichage Localisation : " . $local;
                    }
                } else {
                    if ($local == "") {
                        $lesBiens = $bienRepository->findBy(['is_locatif' => $type]);
                        $titre = 'Affichage ' . $intitType;
                    } else {
                        $lesBiens = $bienRepository->findBy(['is_locatif' => $type, 'cp' => $local]);
                        $titre = "Affichage " . $intitType . " à : " . $local;
                    }
                }
            } elseif ($type == "") {
                if ($local == "") {
                    $lesBiens = $bienRepository->findBy(['id_categorie' => $id, 'is_locatif' => $type]);
                    $titre = "Affichage Catégorie : " . $intitCateg[0]["intitule"];
                } else {
                    $lesBiens = $bienRepository->findBy(['id_categorie' => $id, 'is_locatif' => $type, 'cp' => $local]);
                    $titre = "Affichage : " . $intitCateg[0]["intitule"] . " à : " . $local;
                }
            } else {
                if ($local == "") {
                    $lesBiens = $bienRepository->findBy(['id_categorie' => $id, 'is_locatif' => $type]);
                    $titre = "Affichage : " . $intitCateg[0]["intitule"] . " en " . $intitType;
                } else {
                    $lesBiens = $bienRepository->findBy(['id_categorie' => $id, 'is_locatif' => $type, 'cp' => $local]);
                    $titre = "Affichage Catégorie : " . $intitCateg[0]["intitule"] . " et " . $intitType . " à : " . $local;
                }

            }
        } else {
            $lesBiens = $bienRepository->findAll();
            $titre = 'Affichage des biens';
        }

        return $this->render('bien/index.html.twig', [
            'lesBiens' => $lesBiens,
            'lesCateg' => $categorieRepository->findAll(),
            'localisation' => $bienRepository->getLocalisation(),
            'titre' => $titre,
            'prix' => $price,
        ]);
    }

    /**
     * Il prend l'identifiant d'un bien, trouve le bien dans la base de données et affiche le modèle show.html.twig avec
     * les variables bien et categories
     *
     * @param CategorieRepository categorieRepository C'est le service que nous avons créé à l'étape précédente.
     * @param BienRepository bienRepository Il s'agit du référentiel de l'entité Bien.
     * @param int id L'identifiant du bien à afficher
     *
     * @return Response Le modèle show.html.twig est renvoyé.
     */
    #[Route('/bien/{id}', name: 'app_bien_show')]
    public function show(CategorieRepository $categorieRepository, BienRepository $bienRepository, int $id): Response
    {
        return $this->render('bien/show.html.twig', [
            'categories' => $categorieRepository->findAll(),
            'bien' => $bienRepository->find($id),
        ]);
    }
}

templates/bien/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <form method="post">
        <h1 class="text-center py-4 px-3 text-gray-600 font-bold hover:text-green-600 transition duration-300">Filtrage
            recherche biens</h1>
        <div class="flex justify-center h-10 ">
            <div class="mb-3 xl:w-72 mr-10">
                <select name="Categ" class="form-select appearance-none
      block
      w-full
      px-3
      py-1.5
      text-base
      font-normal
      text-gray-700
      bg-white bg-clip-padding bg-no-repeat
      border border-solid border-gray-300
      rounded
      transition
      ease-in-out
      m-0
      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" aria-label="Default select example">
                    <option value="">-- Aucune option --</option>
                    {% for uneCateg in lesCateg %}
                        <option value="{{ uneCateg.id }}">
                            {{ uneCateg.intitule }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3 xl:w-72 mr-10">
                <select name="local" class="form-select appearance-none
      block
      w-full
      px-3
      py-1.5
      text-base
      font-normal
      text-gray-700
      bg-white bg-clip-padding bg-no-repeat
      border border-solid border-gray-300
      rounded
      transition
      ease-in-out
      m-0
      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" aria-label="Default select example">
                    <option value="">-- Aucune option --</option>
                    {% for uneLocalisation in localisation %}
                        <option value="{{ uneLocalisation.cp }}">
                            {{ uneLocalisation.ville }} - {{ uneLocalisation.cp }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3 xl:w-72 mr-10">
                <select name="Type" class="form-select appearance-none
      block
      w-full
      px-3
      py-1.5
      text-base
      font-normal
      text-gray-700
      bg-white bg-clip-padding bg-no-repeat
      border border-solid border-gray-300
      rounded
      transition
      ease-in-out
      m-0
      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" aria-label="Default select example">
                    <option value="">-- Aucune option --</option>
                    <option value="1">
                        Location
                    </option>
                    <option value="0">
                        Achat
                    </option>
                </select>
            </div>
            <div class="mb-3 w-28 mr-10">
                <input
                        type="number"
                        class="
        form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
      "
                        placeholder="{% if prix == 999999 %}Prix max{% else %} {{ prix }}{% endif %}"
                        name="Price"
                />
            </div>
            <div class="flex space-x-2 justify-center">
                <button type="submit"
                        class="inline-block px-6 py-2.5 bg-green-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">
                    Valider
                </button>
            </div>
        </div>

    </form>
    <h1 class="text-center py-4 px-3 text-gray-600 text-2xl font-bold hover:text-green-600 transition duration-300">{{ titre }}</h1>
    <div class="flex flex-wrap md:space-x-4 justify-center px-4">
        {% for unBien in lesBiens %}
            {% if unBien.prix <= prix %}
                <div class="w-80 h-90 rounded overflow-hidden shadow-lg my-9">
                    <img class="w-full h-48" src="/assets/img/photoSite/{{ unBien.image }}.jpg">
                    <div class="px-6 py-4">
                        <div class="font-bold text-xl mb-2 h-20">{{ unBien.titre }}</div>
                        <p class="text-gray-700 text-base h-32">
                            {{ unBien.description }}
                        </p>
                    </div>
                    <div class="px-6 pt-4 pb-2">
                        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{% if unBien.islocatif == 0 %} Achat {% else %} Location {% endif %}</span>
                        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Disponible</span>
                        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Récent</span>
                    </div>
                    <div class="flex justify-center">
                        <a href="{{ path('app_bien') }}/{{ unBien.id }}">
                            <button class="bg-green-600 hover:bg-blue-500 text-white font-semibold hover:text-white py-2 px-4 border hover:border-transparent rounded mb-2">
                                En savoir plus
                            </button>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/bien/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <main class="py-6 px-4 mb-40 sm:p-6 md:py-10 md:px-8">
        <div class="max-w-4xl mb-40 mx-auto grid grid-cols-1 lg:max-w-5xl lg:gap-x-20 lg:grid-cols-2">
            <div class="relative p-3 col-start-1 row-start-1 flex flex-col-reverse rounded-lg bg-gradient-to-t from-black/75 via-black/0 sm:bg-none sm:row-start-2 sm:p-0 lg:row-start-1">
                <h1 class="mt-1 text-lg font-semibold text-white sm:text-slate-900 md:text-2xl">{{ bien.titre }}</h1>
                <p class="text-sm leading-4 font-medium text-white sm:text-slate-500"><i>#{{ bien.id }}</i></p>
            </div>
            <div class="grid gap-4 col-start-1 col-end-3 row-start-1 sm:mb-6 sm:grid-cols-4 lg:gap-6 lg:col-start-2 lg:row-end-6 lg:row-span-6 lg:mb-0">
                <img src="/assets/img/photoSite/{{ bien.image }}.jpg" alt=""
                     class="w-full h-60 object-cover rounded-lg sm:h-52 sm:col-span-2 lg:col-span-full" loading="lazy">
            </div>
            <dl class="mt-4 text-xs font-medium flex items-center row-start-2 sm:mt-1 sm:row-start-3 md:mt-2.5 lg:row-start-2">
                <dt class="sr-only">Reviews</dt>
                <a href="{{ path('favorite_add', {'id': bien.id}) }}">
                    <dd class="text-green-600 flex items-center">

                        <svg width="24" height="24" fill="none" aria-hidden="true" class="mr-1 stroke-current ">
                            <path d="m12 5 2 5h5l-4 4 2.103 5L12 16l-5.103 3L9 14l-4-4h5l2-5Z" stroke-width="2"
                                  stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <span>Ajouter aux favoris</span>

                    </dd>
                </a>
                <dt class="sr-only">Location</dt>
                <dd class="flex items-center">
                    <svg width="2" height="2" aria-hidden="true" fill="currentColor" class="mx-3 text-slate-300">
                        <circle cx="1" cy="1" r="1"/>
                    </svg>
                    <svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"
                         stroke-linecap="round" stroke-linejoin="round" class="mr-1 text-slate-400 dark:text-slate-500"
                         aria-hidden="true">
                        <path d="M18 11.034C18 14.897 12 19 12 19s-6-4.103-6-7.966C6 7.655 8.819 5 12 5s6 2.655 6 6.034Z"/>
                        <path d="M14 11a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
                    </svg>
                    {{ bien.ville }} - {{ bien.cp }}
                </dd>
            </dl>
            <div class="mt-4 col-start-1 row-start-3 self-center sm:mt-0 sm:col-start-2 sm:row-start-2 sm:row-span-2 lg:mt-6 lg:col-start-1 lg:row-start-3 lg:row-end-4">
                <form id="test" action="/bien" method="post">
                    <input type="hidden" name="Categ" value="{{ bien.idCategorie.id }}"/>
                    <input type="hidden" name="Type" value=""/>
                    <input type="hidden" name="local" value=""/>
                </form>
                <a href='#' class="bg-green-600 text-white text-sm leading-6 font-medium py-2 px-6 rounded-lg"
                   onclick='document.getElementById("test").submit()'>Ce bien appartient à la catégorie
                    <i>{{ bien.idCategorie.intitule }}</a>

                <p class="mt-2 text-sm text-slate-500">{{ bien.description }}</p>
                <p class="mt-2 lg:col-span-1"><b>Type
                        :</b> {% if bien.isLocatif == 1 %} Location {% else %} Vente {% endif %}</p>
                <p class="mt-2 lg:col-span-1"><b>Prix :</b> {{ bien.prix }}€</p>
                <p class="mt-2 lg:col-span-1"><b>Surface disponible :</b> {{ bien.surface }}m²</p>
            </div>
        </div>
    </main>
{% endblock %}