src/Entity/UserFav.php
<?php

namespace App\Entity;

use App\Repository\UserFavRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserFavRepository::class)]
class UserFav
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email_user = null;

    #[ORM\ManyToMany(targetEntity: Bien::class, inversedBy: 'userFavs')]
    private Collection $id_bien;

    #[ORM\Column(length: 255)]
    private ?string $dateEnvoie = null;

    public function __toString()
    {
        return $this->dateEnvoie;
    }

    public function __construct()
    {
        $this->id_bien = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmailUser(): ?string
    {
        return $this->email_user;
    }

    public function setEmailUser(string $email_user): self
    {
        $this->email_user = $email_user;

        return $this;
    }

    /**
     * @return Collection<int, bien>
     */
    public function getIdBien(): Collection
    {
        return $this->id_bien;
    }

    public function addIdBien(bien $idBien): self
    {
        if (!$this->id_bien->contains($idBien)) {
            $this->id_bien->add($idBien);
        }

        return $this;
    }

    public function removeIdBien(bien $idBien): self
    {
        $this->id_bien->removeElement($idBien);

        return $this;
    }

    public function getDateEnvoie(): ?string
    {
        return $this->dateEnvoie;
    }

    public function setDateEnvoie(string $dateEnvoie): self
    {
        $this->dateEnvoie = $dateEnvoie;

        return $this;
    }

    public function getListOfBiens(): array
    {
        return $this->id_bien->toArray();
    }

    public function getListOfBiensById($id): array
    {
        $biens = $this->id_bien->toArray();
        $biensById = [];
        foreach ($biens as $bien) {
            if ($bien->getId() == $id) {
                $biensById[] = $bien;
            }
        }
        return $biensById;
    }

}

src/Controller/UserFavCrudController.php
<?php

namespace App\Controller;

use App\Entity\UserFav;
use App\Form\UserFavType;
use App\Repository\UserFavRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/GererFav')]
class UserFavCrudController extends AbstractController
{
    #[Route('/', name: 'app_user_fav_crud_index', methods: ['GET'])]
    public function index(UserFavRepository $userFavRepository): Response
    {
        return $this->render('user_fav_crud/index.html.twig', [
            'user_favs' => $userFavRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_fav_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserFavRepository $userFavRepository): Response
    {
        $userFav = new UserFav();
        $form = $this->createForm(UserFavType::class, $userFav);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userFavRepository->save($userFav, true);

            return $this->redirectToRoute('app_user_fav_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user_fav_crud/new.html.twig', [
            'user_fav' => $userFav,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_fav_crud_show', methods: ['GET'])]
    public function show(UserFav $userFav): Response
    {
        return $this->render('user_fav_crud/show.html.twig', [
            'user_fav' => $userFav,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_fav_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UserFav $userFav, UserFavRepository $userFavRepository): Response
    {
        $form = $this->createForm(UserFavType::class, $userFav);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userFavRepository->save($userFav, true);

            return $this->redirectToRoute('app_user_fav_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user_fav_crud/edit.html.twig', [
            'user_fav' => $userFav,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_fav_crud_delete', methods: ['POST'])]
    public function delete(Request $request, UserFav $userFav, UserFavRepository $userFavRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$userFav->getId(), $request->request->get('_token'))) {
            $userFavRepository->remove($userFav, true);
        }

        return $this->redirectToRoute('app_user_fav_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user_fav_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_user_fav_crud_delete', {'id': user_fav.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user_fav.id) }}">
    <div class="grid place-items-center">
        <button class="btn p-4 px-6 py-3 text-white bg-gray-500 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out mb-3">Delete</button>
    </div>
</form>

templates/user_fav_crud/_form.html.twig
<div class="grid place-items-center form-control form-group">
    {{ form_start(form) }}
        {{ form_label(form.email_user, null, {'label_attr': {'class': 'block text-gray-700 text-sm font-bold mb-2'}}) }}
        {{ form_widget(form.email_user, {'attr': {'class': 'form-control block px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:outline-none'}}) }}
        {{ form_label(form.dateEnvoie, null, {'label_attr': {'class': 'block text-gray-700 text-sm font-bold mb-2'}} ) }}
        {{ form_widget(form.dateEnvoie, {'attr': {'class': 'form-control block px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:outline-none'}}) }}
        {{ form_label(form.id_bien, 'Id Bien', {'label_attr': {'class': 'block text-gray-700 text-sm font-bold mb-2'}})}}
        {{ form_widget(form.id_bien, {'attr': {'class': 'form-control block px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:outline-none'}}) }}
        <button class="inline-block px-6 py-2.5 text-white bg-gray-500 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out w-full mb-3">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/user_fav_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UserFav{% endblock %}

{% block body %}
    <h1 class="text-4xl font-bold dark:text-white text-center">Edit Favoris</h1>

    {{ include('user_fav_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="grid place-items-center">
        <a href="{{ path('app_user_fav_crud_index') }}">
            <button class="p-4 px-6 py-3 text-white bg-gray-500 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out mb-3">
                Back to list
            </button>
        </a>
    </div>

    {{ include('user_fav_crud/_delete_form.html.twig') }}
{% endblock %}

templates/user_fav_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserFav index{% endblock %}

{% block body %}
    <h1 class="text-center text-4xl font-bold tracking-tight leading-none text-gray-900 md:text-3xl lg:text-3xl dark:text-white">Gerer favoris</h1>

<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <div class="relative shadow-md sm:rounded-lg">
                    <table class="min-w-full w-full text-sm text-left table-auto">
                        <thead class="border-b bg-gray-800">
                            <tr>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">Id</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">User Email</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">Date Envoie</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">Bien Id</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user_fav in user_favs %}
                            <tr class="bg-gray-100 border-b hover:bg-gray-50 dark:hover:bg-gray-600">
                                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ user_fav.id }}</td>
                                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ user_fav.emailUser }}</td>
                                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">{{ user_fav.dateEnvoie }}</td>
                                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                    {% for id in user_fav.idBien %}
                                        {{ id }}
                                    {% endfor %}
                                </td>
                                <td class="text-sm px-6 py-4 whitespace-nowrap">
                                    <a href="{{ path('app_user_fav_crud_show', {'id': user_fav.id}) }}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">show</a>
                                    <a href="{{ path('app_user_fav_crud_edit', {'id': user_fav.id}) }}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">edit</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="11" class="mb-4 text-lg font-normal text-gray-500 dark:text-gray-400">No records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <a href="{{ path('app_user_fav_crud_new') }}" class="flex flex-col items-center text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Create new</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user_fav_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UserFav{% endblock %}

{% block body %}
    <h1 class="text-4xl font-bold dark:text-white text-center">Create new User Favorite</h1>

    {{ include('user_fav_crud/_form.html.twig') }}

    <div class="grid place-items-center">
        <a href="{{ path('app_user_fav_crud_index') }}">
            <button class="p-4 px-6 py-3 text-white bg-gray-500 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out mb-3">Back to list</button>
        </a>
    </div>
{% endblock %}

templates/user_fav_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserFav{% endblock %}

{% block body %}
    <h1 class="text-4xl font-bold dark:text-white text-center">Favoris</h1>

    <table class="table text-sm text-left table-auto content-center grid place-items-center">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user_fav.id }}</td>
            </tr>
            <tr>
                <th>Email user</th>
                <td>{{ user_fav.emailUser }}</td>
            </tr>
            <tr>
                <th>Date Envoie</th>
                <td>{{ user_fav.dateEnvoie }}</td>
            </tr>
            <tr>
                <th>Bien Id</th>
                <td>
                    {% for id in user_fav.idBien %}
                    {{ id }}
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <div class="grid place-items-center">
        <a href="{{ path('app_user_fav_crud_index') }}">
            <button class="p-4 px-6 py-3 text-white bg-gray-500 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out mb-3">
                Back to list
            </button>
        </a>

        <a href="{{ path('app_user_fav_crud_edit', {'id': user_fav.id}) }}">
            <button class="p-4 px-6 py-3 text-white bg-gray-500 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out mb-3">
                Edit
            </button>
        </a>
    </div>

    {{ include('user_fav_crud/_delete_form.html.twig') }}
{% endblock %}